kind: Pod
apiVersion: V1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: sivakumar
  annotations:
    kubernetes.io/created-by: 'Navaneeth'
    jenkins.url: 'http://jenkins.navaneeth.cloud/expense/job/backend/54'
spec:
  containers:
    - name: nginx
      image: nginx