apiVersion: V1
kind: service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:  
    name: frontend
    project: expense
    component: frontend
    environment: dev
ports:
  - protocols: TCP  
    port: 80 #service-port
    targetport: 80 #target-port